### ISSUE TITLE
Not working on chromecast with google tv

### ISSUE THREAD

**Issue by potchin** [xdanik/android-fake-netflix#2]
Juts tried installing this on my Chromecast with google tv and not having any luck. The following is shown in logcat..

```
11-30 20:40:51.997  3526  3937 W HdmiCecController: Failed to send <Text View On> 80:0D with errorCode=1
11-30 20:40:52.025 11305 11305 I SabrinaGlobalKey: launchNetflix: isInteractive: true
11-30 20:40:52.025 11305 11305 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:927 android.content.ContextWrapper.startActivity:383 android.content.ContextWrapper.startActivity:383 com.google.android.chromecast.chromecastservice.GlobalKeyReceiver.launchNetflix:324 com.google.android.chromecast.chromecastservice.GlobalKeyReceiver.onReceive:201 
11-30 20:40:52.026 11305 11305 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startActivity:939 android.app.ContextImpl.startActivity:928 android.content.ContextWrapper.startActivity:383 android.content.ContextWrapper.startActivity:383 com.google.android.chromecast.chromecastservice.GlobalKeyReceiver.launchNetflix:324 
11-30 20:40:52.028  3526  4972 I ActivityTaskManager: START u0 {act=com.netflix.action.NETFLIX_KEY_START flg=0x10020000 pkg=com.netflix.ninja (has extras)} from uid 1000
11-30 20:40:52.030 11305 11305 D AndroidRuntime: Shutting down VM
11-30 20:40:52.031 11305 11305 E AndroidRuntime: FATAL EXCEPTION: main
11-30 20:40:52.031 11305 11305 E AndroidRuntime: Process: com.google.android.chromecast.chromecastservice, PID: 11305
11-30 20:40:52.031 11305 11305 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.google.android.chromecast.chromecastservice.GlobalKeyReceiver: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.netflix.action.NETFLIX_KEY_START flg=0x10020000 pkg=com.netflix.ninja (has extras) }
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3797)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:219)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.netflix.action.NETFLIX_KEY_START flg=0x10020000 pkg=com.netflix.ninja (has extras) }
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:957)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ContextImpl.startActivity(ContextImpl.java:928)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at com.google.android.chromecast.chromecastservice.GlobalKeyReceiver.launchNetflix(GlobalKeyReceiver.java:324)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at com.google.android.chromecast.chromecastservice.GlobalKeyReceiver.onReceive(GlobalKeyReceiver.java:201)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3788)
11-30 20:40:52.031 11305 11305 E AndroidRuntime: 	... 8 more
```

I tried rebuilding/ and reinstalling with an updated intent in the manifest.xml...

```
                <action android:name="com.netflix.action.NETFLIX_KEY_START" />
```
A shot in the dark but no luck.

**Comment by mhssn95** [comment]
try this [https://github.com/mhssn95/Chrome-Cast-Plex-Launcher](url)

**Comment by a-haan** [comment]
@potchin did you ever get any further with this?
